### ISSUE TITLE
Can't run UI of wda-inspector

### ISSUE THREAD

**Issue by Biloleg** [qa-dev/wda-inspector#18]
When I try to run wda-inspector by
./wda-inspector -h=10.5.106.68 -bundleId=<my bundleid>
nothing happens.
No any errors, logs, UI interfaces.

Page
http://10.5.106.68:8100/Status 
return next:
{
  "value" : {
    "state" : "success",
    "os" : {
      "name" : "iOS",
      "version" : "11.0.3"
    },
    "ios" : {
      "simulatorVersion" : "11.0.3",
      "ip" : "10.5.106.68"
    },
    "build" : {
      "time" : "Nov  9 2017 11:17:35"
    }
  },
  "sessionId" : "24E66306-5E10-4C01-9714-D8926030086E",
  "status" : 0
}

so host is correct and web driver is running

**Comment by ghost** [comment]
@Biloleg what happened?

**Comment by Biloleg** [comment]
Sorry, not so clear manual. Everething is ok now.
By the way, how to use xui identificators from java? I use Appium, Eclipse
and your WDA.

Thanks.

9 лист. 2017 р. 16:32 "landrskom" <notifications@github.com> пише:

**Comment by andrskom** [comment]
Xui locators doesn't work with appium. Because it's custom created locators. But Xui locators is faster. You should use https://github.com/qa-dev/WebDriverAgent for good experience with Xui. If u want, we can help u with WDA(Web driver agent).

**Comment by andrskom** [comment]
Can u describe, what is not clear for u in documentation? We will be happy any improvement.

**Comment by Biloleg** [comment]
Hi,

 

It is not specified that inspector should be opened in browser by link http://127.0.0.1:8888. And I expect to run inspector automatically by terminal command 

$ ./wda-inspector -h=127.0.0.1 -bundleId=com.apple.mobilesafari

**Comment by Biloleg** [comment]
Hi,

 

I replace WDA inside Appium by your WDA, but can’t understand how to use XUI locators.

**Comment by andrskom** [comment]
Thank u for feedback. About replace wda, our team will try later and we will write u after that.

**Comment by Biloleg** [comment]
Hello.

 

Please advise me how can I use XUI locators (from Java)? Maybe you have some libs to connect to your WDA which support search and use XUI locators or some examples.

I will be grateful for any help, because I don`t know where to start ☹

**Comment by makhov** [comment]
Hi! Unfortunately we don't use Java and haven't tried to use XUI with java webdriver library.
You should implement your custom locating mechanism:
https://github.com/SeleniumHQ/selenium/blob/master/java/client/src/org/openqa/selenium/By.java#L32

I'll try to write some code to help you to do it asap.

**Comment by makhov** [comment]
@Biloleg, it's easy!
Just use `driver.findElement(String by, String using)` method. For example:
```
driver.findElement("xui", "StaticText[0]");
```

**Comment by Biloleg** [comment]
Hi, 

I have an exception, but can search elements by xui locator in your inspector.

 

Exception in thread "main" org.openqa.selenium.InvalidSelectorException: Locator Strategy 'xui' is not supported for this session (WARNING: The server did not provide any stacktrace information)

Command duration or timeout: 0 milliseconds

For documentation on this error, please visit: http://seleniumhq.org/exceptions/invalid_selector_exception.html

**Comment by andrskom** [comment]
Thank u for feedback. @makhov, do u help us with next step?

**Comment by makhov** [comment]
Ok, I'll try to see it soon.
